# Generated by Django 6.0.6 on 2026-06-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='gateway_transaction_id',
        ),
    ]
