# Generated by Django 6.0.6 on 2026-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('IRT', 'IRT'), ('GOLD', 'GOLD')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
