# Generated by Django 6.0.6 on 2026-06-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='wallet',
            name='available_gold',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='wallet',
            name='locked_gold',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
